### ISSUE TITLE
Valeur des listes en BDD

### ISSUE THREAD

**Issue by camillemonchicourt** [TheoLechemia/BDN#18]
Basculer les valeurs des listes dans des BIB dans la BDD plutôt que de les gérer dans la code : https://github.com/TheoLechemia/BDN/blob/master/Apps/addObs/static/addObs.js#L79-L100

Permet d'être plus générique, de gérer l'intégrité en BDD et de rendre la BDD plus indépendante de l'application.

**Comment by TheoLechemia** [comment]
Fait, mais pas de manière très orthodoxe pour l'instant.
Pour les besoins du module 'addObs' et pour la possibilité d'ajouter facilement des nouveaux templates de saisie, chaque protocole a dans son schéma un table `bib_champs`, qui reprend tous les champs et toutes les valeurs des listes déroulantes. C'est beaucoup plus facile de le gérer comme ça que d'avoir une bib par champs.
Après rien n'empeche d'avoir une bib par champs pour que la BDD soit propre et une bib comme je l'ai faite pour les besoins de l'appli.

**Comment by camillemonchicourt** [comment]
Ouais c'est bien générique. Intéressant. 
Petite remarque, tu devrais afficher les items par ordre alphabétique dans les listes déroulantes.
