### ISSUE TITLE
Interface SYNTHESE - Hauteur 100% et slider vertical dans les blocs

### ISSUE THREAD

**Issue by camillemonchicourt** [TheoLechemia/BDN#2]
On doit slider la page pour voir les différents blocs. 
Je partirai sur une page qui n'a pas de slider vertical, dont la carte fait 100% de hauteur (voir vheight) et dont les sliders verticaux sont dans les blocs (filtres et listes).
Un peu comme dans Geotrek-admin (http://geotrekdemo.ecrins-parcnational.fr).

**Comment by camillemonchicourt** [comment]
Autre exemple. AIRbnb ! :-)

https://www.airbnb.fr/s/Kingston--St%252E-Andrew-Parish--Jama%C3%AFque?guests=2&place_id=ChIJodLehJc_244RQK-3q78h8yQ&checkin=15%2F01%2F2017&checkout=22%2F01%2F2017&adults=2&ss_id=1tvrizwf&source=bb&page=1&allow_override%5B%5D=&ne_lat=18.063059683713135&ne_lng=-76.72563668341718&sw_lat=17.97811154921585&sw_lng=-76.81249734015546&zoom=13&search_by_map=true&price_max=40&s_tag=VY1YJP_x

**Comment by TheoLechemia** [comment]
Je suis en plein dedans.. je galère !

**Comment by camillemonchicourt** [comment]
Oui ça m'a rendu sur la page des communes de GeoNature-atlas et du coup c'est encore en chantier. ... :-)

**Comment by TheoLechemia** [comment]
Avec ça, ça marche bien:
http://stackoverflow.com/questions/7678345/datatables-change-height-of-table-not-working

**Comment by TheoLechemia** [comment]
Après c'est la carte qui est chiante comme elle a une hauteur fixe.
Avec ça:  https://la-cascade.io/pourquoi-height-100-ne-marche-pas/
et la propriété `height: 100vh` il y a moyen de s'en sortir

**Comment by camillemonchicourt** [comment]
Sur la page de VALIDATION c'est top comme ça maintenant !
