### ISSUE TITLE
Nettoyer la recherche par foret

### ISSUE THREAD

**Issue by TheoLechemia** [TheoLechemia/BDN#5]

**Comment by gildeluermoz** [comment]
je ne sais pas s'il s'agit de ça mais on si on a choisi une forêt, on ne peut pas supprimer le critère forêt.
idem pour tous les autres critères de filtre.

**Comment by TheoLechemia** [comment]
Quand tu cliques sur la croix rouge en bas, ça réinitialise les filtres

**Comment by gildeluermoz** [comment]
Oui j'ai vu ça. Mais si tu t'es construit un filtre complexe avec 10 taxons ajoutés un par un et que tu ajoutes par erreur une forêt, tu ne peux pas supprimer seulement le filtre forêt.

**Comment by TheoLechemia** [comment]
Ah oui c'est vrai.. merci
